services:
  ubuntu:
    container_name: ubuntu
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    platform: linux/arm64
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
